# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 19:01
from __future__ import unicode_literals

import multiuploader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiuploaderFile',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField()),
                ('file', models.FileField(max_length=255, upload_to=multiuploader.models._upload_to)),
            ],
            options={
                'verbose_name': 'multiuploader file',
                'verbose_name_plural': 'multiuploader files',
            },
        ),
    ]
