# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiuploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiuploaderfile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='multiuploaderfile',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
